### ISSUE TITLE
ArgumentError: Factory not registered - Rails 5

### ISSUE THREAD

**Issue by Juliusdz** [thoughtbot/factory_girl#1048]
As I found this is very common problem, but I still can not solve it.

I create a user factory (I use Devise), in spec/factories/users.rb:

```
FactoryGirl.define do
  factory :user do
    first_name "Jonas"
    last_name "Sniegas"
    email "test@test.com"
    password "asdfasdf"
    password_confirmation "asdfasdf"
  end
end
```
And try to create it from test console ( `rails c -e test` ):

`FactoryGirl.create(:user)`

And then:

```
ArgumentError: Factory not registered: user
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/registry.rb:24:in `find'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/decorator.rb:10:in `method_missing'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl.rb:85:in `factory_by_name'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:12:in `run'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
  from (irb):1
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
  from /Users/user/Desktop/Ruby/Test/bin/rails:9:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
  from /Users/user/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/user/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Gemfile:

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.3'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'sdoc', '~> 0.4.0', group: :doc


group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'database_cleaner'
end

group :development do

  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'devise', '~> 4.2'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
```
I even tried to add `FactoryGirl.find_definitions` in `before do` block in spec/rails_helper.rb and specify all factories in newly created spec/factories.rb file (because seems docs tells [to do that..](https://github.com/thoughtbot/factory_girl/pull/839/commits/d57d7ed602430c628e1cdec53f6c500477de8a96))

Any help on this?

**Comment by Juliusdz** [comment]
Had to stop Spring. `spring stop`
