### ISSUE TITLE
`rake stats` not working after following 'Testing Your Factories First' post

### ISSUE THREAD

**Issue by cimbriano** [thoughtbot/factory_girl#631]
Referenced post: http://robots.thoughtbot.com/testing-your-factories-first

Rakefile

```ruby
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

MyApp::Application.load_tasks

```

lib/tasks/factories.rake

```ruby
# Part of this technique : http://robots.thoughtbot.com/post/30994874643/testing-your-factories-first
# Runs factory_specs first and fails early if they don't pass,
#   if they do pass then the rest of the specs are run
require 'rspec/core/rake_task'

desc 'Run factory specs.'
RSpec::Core::RakeTask.new(:factory_specs) do |t|
  t.pattern = './spec/factories_spec.rb'
end

task spec: :factory_specs
```

spec/factories_spec.rb
```ruby
# Technique to test is_valid on each factory
#   to avoid failing lots of tests because you forgot to
#   update a factory with a new model validation
#
# Found here : http://robots.thoughtbot.com/post/30994874643/testing-your-factories-first
require 'spec_helper'

FactoryGirl.factories.map(&:name).each do |factory_name|
  describe "The #{factory_name} factory" do
    it 'is valid' do
      FactoryGirl.build(factory_name).should be_valid
    end
  end
end
```

Output of `rake stats`

```
rake aborted!
Not a directory - ./spec/factories_spec.rb
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:40:in `open'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:40:in `foreach'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:40:in `calculate_directory_statistics'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:34:in `block in calculate_statistics'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:34:in `map'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:34:in `calculate_statistics'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/code_statistics.rb:15:in `initialize'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/tasks/statistics.rake:21:in `new'
/Users/chris/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/tasks/statistics.rake:21:in `block in <top (required)>'
Tasks: TOP => stats
(See full trace by running task with --trace)
```

**Comment by joshuaclayton** [comment]
@cimbriano we've actually rolled up this behavior into linting: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#linting-factories
