### ISSUE TITLE
FG calling Fileutils.copy rather than Post.new.copy

### ISSUE THREAD

**Issue by msp** [thoughtbot/factory_girl#828]
I upgraded from Rails 4.2.1 -> 4.2.4 whilst keeping on FG 4.5.0 and I hit this issue when running a db:schema_load on CI.

My app wasn't using the factory so I simply removed it. 

```
factory :post do
    title "This is an amazing post"
    copy "Please don't read me" #this is the clash
```

```
export RAILS_ENV="test"
export RACK_ENV="test"
bundle exec rake db:create db:schema:load --trace
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
** Invoke db:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
TypeError: no implicit conversion of Hash into String
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:1583:in `directory?'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:1583:in `fu_each_src_dest0'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb:401:in `cp'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `copy'
/home/ubuntu/fleetnation/spec/factories/posts.rb:4:in `block (2 levels) in <top (required)>'
/home/ubuntu/fleetnation/vendor/bundle/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/home/ubuntu/fleetnation/vendor/bundle/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/home/ubuntu/fleetnation/spec/factories/posts.rb:2:in `block in <top (required)>'
/home/ubuntu/fleetnation/vendor/bundle/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/home/ubuntu/fleetnation/vendor/bundle/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
/home/ubuntu/fleetnation/vendor/bundle/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
/home/ubuntu/fleetnation/spec/factories/posts.rb:1:in `<top (required)>'
```

**Comment by dandan** [comment]
Is there a good reason why FactoryGirl is loaded during any database rake tasks?

A way to get around the problem is:

    factory :post do |post|
        title "This is an amazing post"
        post.copy "Please don't read me" #this is the clash

**Comment by joshuaclayton** [comment]
@dandan in a test environment, factory_girl_rails's railtie will trigger on `after_initialize` and find and load all factory definitions (assuming the gem is included in the `Gemfile`'s test group).

@msp What seems to be happening here is Rake is mucking with `copy` somehow, based on this line from the backtrace: `/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `copy'`

Instead of using a block variable, you're better off using `add_attribute(:copy, "value")` or `add_attribute(:copy) { "value" }`.

**Comment by msp** [comment]
@joshuaclayton thanks for the tips.
