### ISSUE TITLE
FactoryGirl Linter incompatible with Rails 4

### ISSUE THREAD

**Issue by leoc** [thoughtbot/factory_girl#902]
I am in the process of updating a Rails 3.2 project to Rails 4. It seems like FactoryGirl calls some deprecated methods.

I configured RSPec and factory_girl like so:

```ruby
# ...
RSpec.configure do |config|
  # ...
  config.include FactoryGirl::Syntax::Methods
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
    DatabaseCleaner.clean
    FactoryGirl.reload
    FactoryGirl.lint # line 43
  end
end
```

But when running my test suite I get the following:

```
/usr/local/bundle/gems/factory_girl-4.7.0/lib/factory_girl/linter.rb:12:in `lint!': The following factories are invalid: (FactoryGirl::InvalidFactoryError)

* image - undefined method `transaction_include_action?' for #<Patient:0x00557075d684c8> (NoMethodError)
	from /usr/local/bundle/gems/factory_girl-4.7.0/lib/factory_girl.rb:67:in `lint'
	from /app/spec/spec_helper.rb:43:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:357:in `run'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `block in run_hooks_with'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `each'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1724:in `run_hooks_with'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1679:in `with_suite_hooks'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
	from /usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /usr/local/bundle/gems/zeus-0.15.4/lib/zeus/rails.rb:216:in `test'
	from /usr/local/bundle/gems/zeus-0.15.4/lib/zeus.rb:148:in `block in command'
	from /usr/local/bundle/gems/zeus-0.15.4/lib/zeus.rb:135:in `fork'
	from /usr/local/bundle/gems/zeus-0.15.4/lib/zeus.rb:135:in `command'
	from /usr/local/bundle/gems/zeus-0.15.4/lib/zeus.rb:50:in `go'
	from -e:1:in `<main>'
```

Maybe I am overlooking something?

**Comment by joshuaclayton** [comment]
@leoc that method doesn't look familiar - it might be coming from your factory. It also looks like you're running Zeus, which is notoriously hard to get working correctly (and one of the reasons why the Rails team eventually landed on Spring).

**Comment by leoc** [comment]
Thanks! I found the issue. 

For the record: It is a protected method from Rails 3.2 which has been deprecated with Rails 4.x.
Quick fix was to call the new method `transaction_include_any_action?`. But this is protected aswell... Something to refactor, when everything's been ported...
